## Exercise 1 Code

### 1. Write a Python function to find the Max of three numbers.

In [4]:
def max_of_three(a,b):
    if a > b:
        return a
    else:
        return b

In [5]:
print(max_of_three(max_of_three(3,6),-5))

6


### 2. Difference between np.zeros and np.empty?

In [7]:
import numpy as np

In [16]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [15]:
b = np.empty((2,2))
b

array([[8.90071984e-308, 6.23053954e-307],
       [1.50201822e-307, 4.67296746e-307]])

### 3. Write a NumPy program to multiply a 5x3 matrix by a 3x2 matrix and create a real matrix product

In [28]:
c = np.random.randint(1,10,size = (5,3))
d = np.random.randint(1,10,size = (3,2))
np.matmul(c,d)

array([[35, 21],
       [42, 42],
       [47, 57],
       [42, 58],
       [31, 17]])

### 4. Read the code and answer the following questions:

In [29]:
import numpy as np
arr1 = np.arange(27).reshape(3,3,3)
arr2 = arr1[1].copy()
arr2[2] = 50

### What’s the output of arr1[2,0] and arr2[2,0]?

arr1[2,0] = array([18, 19, 20])

arr2[2,0] = 50

### 5. Read the code and answer the following questions:

In [36]:
import numpy as np
arr1 = np.array([[1,21,3,22,5],[23,7,24,9,25],[11,26,27,28,15]])
arr1

array([[ 1, 21,  3, 22,  5],
       [23,  7, 24,  9, 25],
       [11, 26, 27, 28, 15]])

In [37]:
arr2 = np.array([[21,22,23,24],[25,26,27,28,]])
arr2

array([[21, 22, 23, 24],
       [25, 26, 27, 28]])

### Get array arr2 transformed from arr1 with only one line of code:

In [38]:
arr2 = arr1[arr1>20].reshape(2,4)
arr2

array([[21, 22, 23, 24],
       [25, 26, 27, 28]])

### What’s the output of arr2[-1,-2]?

In [39]:
arr2[-1,-2]

27

### 6. Write a NumPy program to complete the following functions:
(1)Create an array 0-19 of 4,5 shape and print it

(2)Swap axis0 with axis1 and print it

(2)Swap swap column1 with column4 and print it

In [55]:
arr1 = np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
arr1 = arr1.transpose()
arr1

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [58]:
arr1[:,[0,3]] = arr1[:,[3,0]]
arr1

array([[15,  5, 10,  0],
       [16,  6, 11,  1],
       [17,  7, 12,  2],
       [18,  8, 13,  3],
       [19,  9, 14,  4]])

### 7. Write a NumPy program generate 50 random numbers from N(2,3)(the normal distribution with mean 2 and variance 3 and compute their mean and variance.

In [68]:
np.random.seed(1)
arr1 = np.random.normal(2,3,50)
arr1

array([ 6.87303609,  0.16473076,  0.41548474, -1.21890587,  4.59622289,
       -4.90461609,  7.23443529, -0.2836207 ,  2.95711729,  1.25188887,
        6.38632381, -4.18042213,  1.03274839,  0.84783694,  5.40130833,
       -1.2996738 ,  1.48271538, -0.63357525,  2.12664124,  3.74844564,
       -1.30185753,  5.43417113,  4.70477216,  3.50748302,  4.70256785,
       -0.05118358,  1.63132932, -0.8073083 ,  1.19633576,  3.5910664 ,
       -0.07498226,  0.80973942, -0.0615181 , -0.53561692, -0.01373839,
        1.9620062 , -1.35193105,  2.70324709,  6.97940653,  4.22613248,
        1.42449334, -0.66288689, -0.24147488,  7.0773638 ,  2.15242326,
        0.08901306,  2.57274645,  8.30076541,  2.36047686,  3.85160933])

In [69]:
np.random.seed(2)
arr1 = np.random.normal(2,3,50)
arr1

array([ 0.74972646,  1.83119952, -4.40858829,  6.92081243, -3.38030676,
       -0.5252421 ,  3.50864425, -1.73586426, -1.17385666, -0.72702284,
        3.65436213,  8.87662404,  2.12461818, -1.35377634,  3.61717496,
        0.2115209 ,  1.94260851,  5.52500366, -0.24361285,  2.02707575,
       -0.63432368,  1.53069749,  2.76971136, -0.96633715,  0.9835341 ,
        1.29144791,  0.08703496, -1.56283686, -2.26365168,  1.53951441,
        1.19282912,  8.69410037, -5.30430273,  2.33817951,  3.11133361,
        6.07890159,  3.50557162, -0.53264111,  2.00002928,  3.62705772,
        1.05947541,  4.31303521, -3.60427196,  7.193554  ,  6.40303403,
        0.99296798,  3.83402234,  2.14391178, -0.48740587,  2.26313066])

In [61]:
arr1.mean()

2.222436625707705

In [64]:
arr1.var()

9.266273564467763