In [1]:
import pandas as pd
from sklearn.preprocessing import normalize
from sklearn.linear_model import LinearRegression
import numpy as np
from sklearn.model_selection import train_test_split

In [5]:
# l1 normalization - absolute value normalization
X = [[ 1., -1., 2.],
    [ 2., 0., 0.],
    [ 0., 1., -1.]]
X_normalized_1 = normalize(X,norm = 'l1')
X_normalized_1

array([[ 0.25, -0.25,  0.5 ],
       [ 1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.5 , -0.5 ]])

In [6]:
# l2 normalization - euclidean normalization
X = [[ 1., -1., 2.],
    [ 2., 0., 0.],
    [ 0., 1., -1.]]
X_normalized_2 = normalize(X,norm = 'l2')
X_normalized_2

array([[ 0.40824829, -0.40824829,  0.81649658],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])

In [7]:
# max normalization
X = [[ 1., -1., 2.],
    [ 2., 0., 0.],
    [ 0., 1., -1.]]
X_normalized_3 = normalize(X,norm = 'max')
X_normalized_3

array([[ 0.5, -0.5,  1. ],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  1. , -1. ]])